import { writeFileSync, unlinkSync, mkdirSync, rmSync } from "fs";
import { join, dirname } from "path";
import { tmpdir } from "os";
import { nanoid } from "nanoid";
import {
  runComposeCommand,
  downProject,
} from "./compose-cli";
import {
  ensureNetwork,
  connectTraefikToNetwork,
} from "./docker-engine";
import { ActionFailedError } from "./errors";
import { runLoggedAction, type ActionIdentity } from "./logged-action";

type SecretFile = {
  filePath: string;
  value: string;
};

type DeployOptions = {
  composePath: string;
  /**
   * The exact compose bytes Docker applies. `deployStack` owns the snapshot
   * lifecycle: it freezes the bytes to a sibling temp file in the same
   * directory (same `cwd` + relative-path resolution as the live file),
   * runs `compose -f <temp>`, and deletes the temp in `finally`. Callers
   * validate/generate bytes, then hand them over — "validated === applied"
   * is a property of the attempt, not a convention each caller re-implements
   * with its own write/rm block. Always snapshotted from bytes: there is no
   * "apply the live path as-is" mode, so no caller can skip the freeze.
   */
  composeBytes: string;
  /**
   * Promote the applied bytes to the live path as part of the same attempt.
   * Stack deploy leaves this off (the live file already holds the validated
   * bytes); core deploy sets it (the generated template must become live).
   * The promote runs inside the attempt before success is returned, so a
   * failed write falls into the same catch: secrets wiped, containers
   * brought back down, error thrown — never "containers up + stale live
   * file + success log".
   */
  commitLive?: boolean;
  envVars: Record<string, string>;
  secretFiles?: SecretFile[];
  networkName?: string;
  // Required (not optional): a failed attempt compensates via `downProject`
  // by name, so deploy must always know the teardown identity.
  projectName: string;
  onOutput?: (chunk: string) => void;
};

export type { DeployOptions };

export function escapeEnvValue(value: string): string {
  if (!/[\s#"'\\]/.test(value)) return value;
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
}

function writeEnvFile(envVars: Record<string, string>): string {
  const envPath = join(tmpdir(), `laber-env-${Date.now()}.env`);
  const content = Object.entries(envVars)
    .map(([k, v]) => `${k}=${escapeEnvValue(v)}`)
    .join("\n");
  writeFileSync(envPath, content, { encoding: "utf-8", mode: 0o600 });
  return envPath;
}

function writeSecretFiles(files: SecretFile[]): void {
  for (const { filePath, value } of files) {
    mkdirSync(dirname(filePath), { recursive: true, mode: 0o700 });
    writeFileSync(filePath, value, { encoding: "utf-8", mode: 0o600 });
  }
}

function removeSecretFiles(files: SecretFile[]): void {
  for (const { filePath } of files) {
    try {
      rmSync(filePath, { force: true });
    } catch {
      // best-effort cleanup
    }
  }
}

/**
 * Single failure contract: returns the deploy output on success, throws
 * `ActionFailedError` (via `runComposeCommand`) on a nonzero exit — deploy
 * never reads exit codes itself. Freshly-written secret files are wiped in
 * the catch below; on success they stay (running containers mount these
 * paths). `runLoggedAction` maps the throw to the contextual failure message,
 * so the message here stays short — the transcript is already in the
 * activity stream and deployment log.
 *
 * One atomic success contract: success means "`up -d` + Traefik attached".
 * Any failure after this attempt wrote secrets or started containers is
 * compensated before the throw — secrets wiped, containers brought back
 * down via the same `downProject` teardown stop uses — so an `"error"`
 * status never hides running containers or secret files on disk. The
 * compensating `down` streams into the same transcript; if it also fails,
 * the original error is what throws.
 */
export async function deployStack(
  options: DeployOptions
): Promise<{ output: string }> {
  if (options.networkName) {
    await ensureNetwork(options.networkName);
  }

  let envFilePath: string | undefined;
  let secretsWritten = false;
  let composeUp = false;
  let snapshotPath: string | undefined;
  let composePath = options.composePath;
  const secretFiles = options.secretFiles ?? [];
  try {
    // Freeze the validated/generated bytes under this attempt: live-tree
    // writers (compose save, sync pull) cannot swap the file between the
    // caller's gate check and `up -d`.
    snapshotPath = `${options.composePath}.deploy-${nanoid(8)}.tmp`;
    writeFileSync(snapshotPath, options.composeBytes, "utf-8");
    composePath = snapshotPath;

    if (secretFiles.length > 0) {
      // Secret paths are already absolute (resolved by the parse gate
      // against the compose file); write them in exactly one place here.
      writeSecretFiles(secretFiles);
      secretsWritten = true;
    }

    const envArgs: string[] = [];
    if (Object.keys(options.envVars).length > 0) {
      envFilePath = writeEnvFile(options.envVars);
      envArgs.push("--env-file", envFilePath);
    }

    // Single env channel: everything the stack needs travels via --env-file.
    // (execCompose still inherits process.env, but stack vars are no longer
    // overlaid a second time, so there is only one fact to fix.)
    // A failed compose run must not leave freshly-written secret files behind:
    // the catch below wipes them (removal is idempotent), so no cleanup
    // hook is needed on the shared CLI — one wipe site only.
    const { output: base } = await runComposeCommand(
      composePath,
      [...envArgs, "up", "-d"],
      options.projectName,
      options.onOutput
    );
    composeUp = true;

    let output = base;

    // Traefik attach is part of the deploy success contract, not a warning:
    // the product contract is "reachable via Traefik", and the stack status
    // becomes `"deployed"` on success — a soft warning here would mark a
    // stack live while ingress is broken. A failure throws, so the shared
    // status machine moves the stack to `"error"` and the transcript keeps
    // the reason (the wire message stays short by design).
    if (options.networkName) {
      try {
        await connectTraefikToNetwork(options.networkName);
      } catch (e) {
        const reason = e instanceof Error ? e.message : String(e);
        const detail = `Could not attach Traefik to network ${options.networkName}: ${reason}\n`;
        output += detail;
        options.onOutput?.(detail);
        throw new ActionFailedError(
          `Could not attach Traefik to network ${options.networkName}: ${reason}`
        );
      }
    }

    // Success: running containers mount the secret files, so they stay.
    // Core promote is part of the same attempt: the generated bytes become
    // the live template before success is returned, so a failed write
    // compensates (down + secret wipe) via the catch below instead of
    // leaving "containers up + stale live file + success log".
    if (options.commitLive) {
      writeFileSync(options.composePath, options.composeBytes, "utf-8");
    }
    secretsWritten = false;
    return { output };
  } catch (e) {
    // Compensate this attempt only: wipe secrets it wrote, bring down
    // containers it started. Removal is idempotent, and this catch is the
    // one wipe site (the shared CLI carries no cleanup hook by design).
    if (secretsWritten && secretFiles.length > 0) {
      removeSecretFiles(secretFiles);
    }
    if (composeUp) {
      try {
        await downProject({
          projectName: options.projectName,
          composePath,
          onOutput: options.onOutput,
        });
      } catch (downError) {
        options.onOutput?.(
          `Deploy cleanup (down) also failed: ${downError instanceof Error ? downError.message : "unknown error"}\n`
        );
      }
    }
    throw e;
  } finally {
    if (envFilePath) {
      try {
        unlinkSync(envFilePath);
      } catch {
        // ignore cleanup errors
      }
    }
    if (snapshotPath) {
      try {
        rmSync(snapshotPath, { force: true });
      } catch {
        // best-effort snapshot cleanup; the deploy outcome is what matters.
      }
    }
  }
}

/**
 * The one logged-deploy shell, next to the Docker/compensation policy it
 * wraps: stack `deployStackByName` and `deployCore` only resolve inputs +
 * identity, then run through here. `compose-actions.ts` stays the argv
 * lifecycle table (stop/restart/pull) only.
 */
export function runLoggedDeploy(options: {
  title: string;
  action: string;
  identity: ActionIdentity;
  failureMessage?: string;
  deploy: Omit<DeployOptions, "onOutput">;
}): Promise<{ output: string }> {
  return runLoggedAction({
    title: options.title,
    action: options.action,
    identity: options.identity,
    failureMessage: options.failureMessage,
    run: async (onOutput) => {
      const result = await deployStack({ ...options.deploy, onOutput });
      return { output: result.output };
    },
  });
}
